import tkinter

master_window = tkinter.Tk()


menu1 = tkinter.Menu(master_window)
master_window.config(menu=menu1)
filemenu = tkinter.Menu(menu1, tearoff=0)
menu1.add_cascade(label="File", menu=filemenu)
filemenu.add_command(label="New Text File")
filemenu.add_command(label="New File...")
filemenu.add_command(label="New Window")
filemenu.add_command(label="New Windo with Profile")
filemenu.add_separator()
filemenu.add_command(label="Open File...")
filemenu.add_command(label="Open Folder..")
filemenu.add_command(label="Open Workspace from Folder")
filemenu.add_command(label="Open Recent")
filemenu.add_separator()
filemenu.add_command(label="Add folder to workspace...")
filemenu.add_command(label="Save workspace as..")
filemenu.add_command(label="Duplicate workspace..")
filemenu.add_separator()
filemenu.add_command(label="Save")
filemenu.add_command(label="Save as...")
filemenu.add_command(label="Save all")
filemenu.add_separator()
filemenu.add_command(label="Share >")
filemenu.add_separator()
filemenu.add_command(label="Auto Save")
filemenu.add_command(label="Preferences")
filemenu.add_separator()
filemenu.add_command(label="Revert File")
filemenu.add_command(label="Close Editor")
filemenu.add_command(label="Close Folder")
filemenu.add_command(label="Close Window")
filemenu.add_separator()
filemenu.add_command(label="Exit", command=master_window.destroy)
editmenu=tkinter.Menu(menu1, tearoff=0)
menu1.add_cascade(label="Edit", menu=editmenu)
editmenu.add_command(label="Undo")
editmenu.add_command(label="Redo")
editmenu.add_separator()
editmenu.add_command(label="Cut")
editmenu.add_command(label="Copy")
editmenu.add_command(label="Paste")
editmenu.add_separator()
editmenu.add_command(label="Find")
editmenu.add_command(label="Replace")
editmenu.add_separator()
editmenu.add_command(label="Find in Files")
editmenu.add_command(label="Replace in files")
editmenu.add_separator()
editmenu.add_command(label="Toggle lin comment")
editmenu.add_command(label="Toggle block comment")
editmenu.add_command(label="Emmet: Expand Abbreviation")
editmenu.add_separator()
editmenu.add_command(label="Exit", command=master_window.destroy)
jejemenu=tkinter.Menu(menu1, tearoff=0)
menu1.add_cascade(label="Jeje", menu=jejemenu)
jejemenu.add_command(label="Do you")
jejemenu.add_command(label="wear wigs")
jejemenu.add_separator()
jejemenu.add_command(label="Have you")
jejemenu.add_command(label="worn wigs")
jejemenu.add_separator()
jejemenu.add_command(label="Will you")
jejemenu.add_command(label="wear wigs")
jejemenu.add_separator()
jejemenu.add_command(label="When will you")
jejemenu.add_command(label="wear wigs")
jejemenu.add_separator()
jejemenu.add_command(label="Exit", command=master_window.destroy)
master_window.mainloop()